version: '3'

x-default-app: &default-app
  image: maven:3.9.4-eclipse-temurin-20-alpine
  command: sh dev-run.sh
  working_dir: /usr/src/app


services:

  product:
    <<: *default-app
    volumes:
      - ./product-service:/usr/src/app:rw
      - ${MAVEN_CONFIG_FOLDER}:/root/.m2   # comment this line if you do not want to use you local maven config

  eureka:
    <<: *default-app
    volumes:
      - ./service-registry:/usr/src/app:rw
      - ${MAVEN_CONFIG_FOLDER}:/root/.m2   # comment this line if you do not want to use you local maven config
