version: '3'

x-common-environment: &common-environment
  APPLICATION_PROFILE: ${APPLICATION_PROFILE}
  EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://eureka:${EUREKA_SERVICE_PORT}/eureka

#x-keycloak-service: &keycloak-service
#  - KEYCLOAK_SERVICE=keycloak

services:

  eureka:
    container_name: eureka
    ports:
      - "${EUREKA_SERVICE_PORT}:${EUREKA_SERVICE_PORT}"
    environment:
      <<: *common-environment
      SERVER_PORT: ${EUREKA_SERVICE_PORT}
    restart: unless-stopped
    networks:
      - net_backend

  product:
    container_name: product
    ports:
      - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
    environment:
      <<: *common-environment
      SERVER_PORT: ${PRODUCT_SERVICE_PORT}
#      DATABASE_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/${QUESTION_DATABASE}?authSource=admin
    restart: unless-stopped
    networks:
      - net_backend
    depends_on:
      - eureka
#      - mongo
    links:
      - "eureka"

networks:
  net_backend:
    driver: bridge
